# Generated by Django 4.0.4 on 2022-06-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=22.6, max_digits=4),
            preserve_default=False,
        ),
    ]
