# Generated by Django 4.0.4 on 2022-05-16 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caloricity',
            options={'verbose_name_plural': 'caloricities'},
        ),
        migrations.AlterField(
            model_name='item',
            name='caloricity',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item.caloricity'),
        ),
    ]
