# Generated by Django 4.0.4 on 2022-05-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_caloricity_options_alter_item_caloricity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='caloricity',
        ),
        migrations.AddField(
            model_name='caloricity',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='item.item'),
        ),
    ]
