# Generated by Django 4.0.4 on 2022-05-17 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_caloricity_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloricity',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caloricity', to='item.item'),
        ),
    ]
